### ISSUE TITLE
Progress bar for pull and push

### ISSUE THREAD

**Issue by acmpo6ou** [Aldeshov/ADBFileExplorer#3]
Hi!

I love ADBFileExplorer! There is no progress bar when pushing to or pulling from the device, however. Also, I've noticed that you are using a custom wrapper around adb instead of a library like `python-adb`, which has this functionality implemented: you can get transfer progress when pushing and pulling.

So, you could use `python-adb` to add a progress bar.
I hope it will help you!

**Comment by Aldeshov** [comment]
Hi! Thank you for your feedback!
Okay, I will try to add it as a variant
